spring:
  application:
    name: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://book-wave-db.cze40aa02479.ap-northeast-2.rds.amazonaws.com:3306/bw
    username: admin
    password: Dldirtm98!

  logging:
    level:
      root: INFO
      org.springframework.security: DEBUG
      com.test.demo: DEBUG  # 패키지별 로그 레벨 설정

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "876a1a6b5fad60d7b3b181b59e1a0046"
            redirect-uri: "http://localhost:3000/kakao/callback"
            authorization-grant-type: "authorization_code"
            scope: "profile, email"
            client-name: "kakao"
          naver:
            client-id: "ezcqOn0v8G6iwjVAX5yj"
            client-secret: "zXnmjUqVQR"
            redirect-uri: "http://localhost:3000/naver/callback"
            authorization-grant-type: "authorization_code"
            scope: "name, email"
            client-name: "naver"
        provider:
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-name-attribute: id
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-name-attribute: response
  jwt:
    secret: 92aef2ea55fdec03c597ac1dc962287dddf16b8ce48ff3a851b734c942a3eed310591848fe9b386fd1d3ec8d588d03f5a84bb99bcd036423134f19b95a86279859928e9547bff66d89030f8bf5be1630d8a5c352da674d47c5b5323a803f1d61f0be2987c4d8b6378b30438461e34bee8af54610689957447ba4c217ddd5300259bf60a8c13c7c7ea9bde1783d29ee33c64d2a1d1f860bcd28c81ab6715cdb54d481a145c5012437e326460baa36d82d6376429cf12f5ca070da6925a472cc06b7f643984372b9c55e8fd71ed507ea4146551e64b2b6e0c4ce663615e49887647c4e480920f4ab8241ec865f286450a1e386433ef06e6ff1b587f32fee7a21fb
  web:
    cors:
      allowed-origins: "http://localhost:3000"  # React 앱의 URL
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: "*"
      allow-credentials: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: junyoun9dev@gmail.com
    password: hwsqgvsgugczubyn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379